name: tfhorovod

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - bokeh=1.4
  - cmake=3.16
  - cudnn=7.6
  - cupti=10.1
  - cxx-compiler=1.0
  - jupyterlab=1.2
  - mpi4py=3.0 # installs cuda-aware openmpi
  - nccl=2.5
  - nodejs=13
  - nvcc_linux-64=10.1
  - pip=20.1
  - pip:
    - mxnet-cu101mkl==1.6.* # makes sure frameworks are installed prior to horovod
    - tensorflow-gpu==2.3.*
    - -r file:requirements.txt
  - python=3.7
  - tensorboard=2.3
